

export const roleAction = {

  ROLE_FETCH: Symbol('ROLE_FETCH'),

  CHANGE_ROLE_STORE_SAGA: Symbol('CHANGE_ROLE_STORE_SAGA'),
  CHANGE_ROLE_STORE: Symbol('CHANGE_ROLE_STORE'),

  GET_ROLE_LIST_SAGA: Symbol('GET_ROLE_LIST_SAGA'),
  GET_MENU_LIST_SAGA: Symbol('GET_MENU_LIST_SAGA'),
  GET_DEFAULT_MENU_LIST_SAGA: Symbol('GET_DEFAULT_MENU_LIST_SAGA'),

  GET_ROLE_FETCH_SUCCESS: Symbol('GET_ROLE_FETCH_SUCCESS'),

  CREATE_ROLE_SAGA: Symbol('CREATE_ROLE_SAGA'),

  EDIT_ROLE_SAGA: Symbol('EDIT_ROLE_SAGA'),

  DELETE_ROLE_SAGA: Symbol('DELETE_ROLE_SAGA'),

  RESET_ROLE_SAGA: Symbol('RESET_ROLE_SAGA'),
  RESET_ROLE: Symbol('RESET_ROLE'),

  getOperatetype: Symbol('getOperatetype'),
}





