

export const ENTERPRISE_FETCH = 'ENTERPRISE_FETCH';

export const CHANGE_ENTERPRISE_PAGE = 'CHANGE_ENTERPRISE_PAGE';
export const CHANGE_ENTERPRISE_PAGE_SAGA = 'CHANGE_ENTERPRISE_PAGE_SAGA';

export const GET_ENTERPRISE_LIST_SAGA = 'GET_ENTERPRISE_LIST_SAGA';
export const GET_ENTERPRISE_LIST_SUCCESS = 'GET_ENTERPRISE_LIST_SUCCESS';

export const CHANGE_SELECTED_ENTERPRISE_SAGA = 'CHANGE_SELECTED_ENTERPRISE_SAGA';
export const CHANGE_SELECTED_ENTERPRISE_SUCCESS = 'CHANGE_SELECTED_ENTERPRISE_SUCCESS';




