export const personnelGpsAction = {
  // GET_ALLSTATIONDATA_SAGA: Symbol('GET_ALLSTATIONDATA_SAGA'),//	获取多电站数据分析
  PERSONNELGPS_FETCH: Symbol(' PERSONNELGPS_FETCH'),//loading
  GET_PERSONNELGPS_FETCH_SUCCESS: Symbol('GET_PERSONNELGPS_FETCH_SUCCESS'),//请求成功 
  CHANGE_PERSONNELGPS_STORE_SAGA: Symbol('CHANGE_PERSONNELGPS_STORE_SAGA'),
  CHANGE_PERSONNELGPS_STORE: Symbol('CHANGE_PERSONNELGPS_STORE'),
  getPersonnelGpsData:Symbol('getPersonnelGpsData'),

 

}
