

export const ENTERPRISE_FETCH = 'ENTERPRISE_FETCH';

export const GET_ENTERPRISE_ATTR_CHANGE_SAGA = 'GET_ENTERPRISE_ATTR_CHANGE_SAGA';
export const GET_ENTERPRISE_ATTR_CHANGE_SUCCESS = 'GET_ENTERPRISE_ATTR_CHANGE_SUCCESS';
export const GET_ENTERPRISE_COMMON_FETCH_SUCCESS = 'GET_ENTERPRISE_COMMON_FETCH_SUCCESS';

export const GET_ENTERPRISE_LIST_SAGA = 'GET_ENTERPRISE_LIST_SAGA';
export const CHANGE_SELECTED_ENTERPRISE_SAGA = 'CHANGE_SELECTED_ENTERPRISE_SAGA';





