

export const commonAction = {
  COMMON_FETCH: Symbol('COMMON_FETCH'),
  CHANGE_COMMON_STORE_SAGA: Symbol('CHANGE_COMMON_STORE_SAGA'),
  CHANGE_COMMON_STORE: Symbol('CHANGE_COMMON_STORE'),
  GET_STATIONS_SAGA: Symbol('GET_STATIONS_SAGA'),
  //获取所有设备类型，用户权限相关
  GET_DEVICETYPES_SAGA: Symbol('GET_DEVICETYPES_SAGA'),
  //获取某电站下所有设备类型
  GET_STATION_DEVICETYPES_SAGA: Symbol('GET_STATION_DEVICETYPES_SAGA'),
  GET_STATION_DEVICEMODEL_SAGA: Symbol('GET_STATION_DEVICEMODEL_SAGA'), // 获取设备型号
  GET_STATION_DEVICEPOINT_SAGA: Symbol('GET_STATION_DEVICEPOINT_SAGA'), // 获取设备测点
  GET_DEVICES_SAGA: Symbol('GET_DEVICES_SAGA'),
  GET_PARTITIONS_SAGA: Symbol('GET_PARTITIONS_SAGA'),
  REFRESHTOKEN_SAGA: Symbol('REFRESHTOKEN_SAGA'), //refreshToken -get 

  GET_ALL_DEPARTMENT_SAGA: Symbol('GET_ALL_DEPARTMENT_SAGA'), // 获取企业下所有部门(含层级关系);
  GET_COMMON_FETCH_SUCCESS: Symbol('GET_COMMON_FETCH_SUCCESS'), // 普通api请求成功
  GET_SLICE_DEVICES_SAGA: Symbol('GET_SLICE_DEVICES_SAGA'),//获取光伏截取数据
}

