

export const singleStationAction = {
  GET_SINGLE_STATION_SAGA: Symbol('GET_SINGLE_STATION_SAGA'),//	获取单电站实时数据
  SINGLE_STATION_FETCH: Symbol('SINGLE_STATION_FETCH'),//loading
  GET_SINGLE_STATION_SUCCESS:Symbol('GET_SINGLE_STATION_SUCCESS'),//请求成功
  GET_SINGLE_STATION_FAIL: Symbol('GET_SINGLE_STATION_FAIL'),//请求失败
  CHANGE_SINGLE_STATION_STORE_SAGA: Symbol('CHANGE_SINGLE_STATION_STORE_SAGA'),//请求改变单电站store数据
  CHANGE_SINGLE_STATION_STORE: Symbol('CHANGE_SINGLE_STATION_STORE'),//改变单电站store数据成功
  GET_STATION_LIST_SAGA: Symbol('GET_STATION_LIST_SAGA'),//获取电站列表
  GET_CAPABILITY_DIAGRAM_SAGA: Symbol('GET_CAPABILITY_DIAGRAM_SAGA'),//获取出力图数据
  GET_MONITOR_POWER_SAGA: Symbol('GET_MONITOR_POWER_SAGA'),//获取理论发电量 实际发电量数据
  GET_OPERATOR_LIST_SAGA: Symbol('GET_OPERATOR_LIST_SAGA'),//运维人员列表
  GET_WEATHER_LIST_SAGA: Symbol('GET_WEATHER_LIST_SAGA'),//未来天气数据
  GET_ALARM_LIST_SAGA: Symbol('GET_ALARM_LIST_SAGA'),//告警数统计
  GET_WORK_LIST_SAGA: Symbol('GET_WORK_LIST_SAGA'),//工单数统计
  GET_DEVICE_TYPE_FLOW_SAGA: Symbol('GET_DEVICE_TYPE_FLOW_SAGA'),//设备类型示意图
  GET_PVMODULE_LIST_SAGA: Symbol('GET_PVMODULE_LIST_SAGA'),//光伏组件列表
  GET_INVERTER_LIST_SAGA: Symbol('GET_INVERTER_LIST_SAGA'),//组串式逆变器列表
  GET_BOXTRANSFORMER_LIST_SAGA: Symbol('GET_BOXTRANSFORMER_LIST_SAGA'),//箱变列表
  GET_CONFLUENCEBOX_LIST_SAGA: Symbol('GET_CONFLUENCEBOX_LIST_SAGA'), // 获取汇流箱列表
  GET_STATION_DEVICELIST_SAGA: Symbol('GET_STATION_DEVICELIST_SAGA'),//获取单电站设备列表
  EDIT_MONTH_YEAR_DATA_SAGA:Symbol('EDIT_MONTH_YEAR_DATA_SAGA'),//编辑月/年累计发电量
  RESET_SINGLE_STATION_STORE:Symbol('RESET_SINGLE_STATION_STORE'),//重置store状态
  RESET_SINGLE_STATION_SUCCESS:Symbol('RESET_SINGLE_STATION_SUCCESS'),//重置store状态成功
}