export const operateAnalysisAction = {
  GET_OPERATESTATIONDATA_SAGA: Symbol('GET_OPERATESTATIONDATA_SAGA'),//	获取该电站生产数据分析
  OPERATESTATIONDATA_FETCH: Symbol(' OPERATESTATIONDATA_FETCH'),//loading
  GET_OPERATESTATIONDATA_FETCH_SUCCESS: Symbol('GET_OPERATESTATIONDATA_FETCH_SUCCESS'),//请求成功 
  CHANGE_OPERATESTATIONDATA_STORE_SAGA: Symbol('CHANGE_OPERATESTATIONDATA_STORE_SAGA'),//改变默认参数
  CHANGE_OPERATESTATIONDATA_STORE: Symbol('CHANGE_OPERATESTATIONDATA_STORE'),//改变默认参数
 
 

}
