
export const COMMON_FETCH = 'COMMON_FETCH';   

export const GET_STATIONS_SAGA = 'GET_STATIONS_SAGA';
export const GET_STATIONS_SAGA_SUCCESS = 'GET_STATIONS_SAGA_SUCCESS';
export const GET_STATIONS_SAGA_FAIL = 'GET_STATIONS_SAGA_FAIL';

export const GET_DEVICETYPES_SAGA = 'GET_DEVICETYPES_SAGA';
export const GET_DEVICETYPES_SAGA_SUCCESS = 'GET_DEVICETYPES_SAGA_SUCCESS';
export const GET_DEVICETYPES_SAGA_FAIL = 'GET_DEVICETYPES_SAGA_FAIL';

export const GET_DEVICES_SAGA = 'GET_DEVICES_SAGA';
export const GET_DEVICES_SAGA_SUCCESS = 'GET_DEVICES_SAGA_SUCCESS';
export const GET_DEVICES_SAGA_FAIL = 'GET_DEVICES_SAGA_FAIL';

export const GET_PARTITIONS_SAGA = 'GET_PARTITIONS_SAGA';
export const GET_PARTITIONS_SAGA_SUCCESS = 'GET_PARTITIONS_SAGA_SUCCESS';
export const GET_PARTITIONS_SAGA_FAIL = 'GET_PARTITIONS_SAGA_FAIL';

