//login
export const GET_COMPINFO_SAGA = 'GET_COMPINFO_SAGA';
export const GET_COMPINFO_SUCCESS = 'GET_COMPINFO_SUCCESS';
export const GET_COMPINFO_FAIL = 'GET_COMPINFO_FAIL';
export const LOGIN_SAGA = 'LOGIN_SAGA';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//forget
//验证手机号&发送验证码
export const CHECK_PHONE_SAGA = 'CHECK_PHONE_SAGA';
export const CHECK_PHONE_FAIL = 'CHECK_PHONE_FAIL';
export const SEND_CODE_SAGA = 'SEND_CODE_SAGA';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';
export const CHECK_CODE_SAGA = 'CHECK_CODE_SAGA';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_FAIL = 'CHECK_CODE_FAIL';
//修改密码
export const CHANGE_PSW_SAGA = 'CHANGE_PSW_SAGA';
export const CHANGE_PSW_SUCCESS = 'CHANGE_PSW_SUCCESS';
export const CHANGE_PSW_FAIL = 'CHANGE_PSW_FAIL';


//signup
export const GET_COMPINFO_SU_SAGA = 'GET_COMPINFO_SU_SAGA';
export const GET_COMPINFO_SU_SUCCESS = 'GET_COMPINFO_SU_SUCCESS';
export const GET_COMPINFO_SU_FAIL = 'GET_COMPINFO_SU_FAIL';
export const SIGNUP_SAGA = 'SIGNUP_SAGA';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const CHECK_PHONE_SU_SAGA = 'CHECK_PHONE_SU_SAGA';
export const CHECK_PHONE_SU_FAIL = 'CHECK_PHONE_SU_FAIL';




