//login
export const GET_COMINFO_SAGA = 'GET_COMINFO_SAGA';
export const GET_COMINFO_SUCCESS = 'GET_COMINFO_SUCCESS';
export const GET_COMINFO_FAIL = 'GET_COMINFO_FAIL';
export const GET_LOGIN_SAGA = 'GET_LOGIN_SAGA';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';