//login
export const GET_COMINFO_SAGA = 'GET_COMINFO_SAGA';
export const GET_COMINFO_SUCCESS = 'GET_COMINFO_SUCCESS';
export const GET_COMINFO_FAIL = 'GET_COMINFO_FAIL';
export const GET_LOGIN_SAGA = 'GET_LOGIN_SAGA';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';

//forget
//验证手机号&发送验证码
export const CHECK_PHONE_SAGA = 'CHECK_PHONE_SAGA';
export const CHECK_PHONE_SUCCESS = 'CHECK_PHONE_SUCCESS';
export const CHECK_PHONE_FAIL = 'CHECK_PHONE_FAIL';
export const GET_CODE_SAGA = 'GET_CODE_SAGA';
export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS';
export const GET_CODE_FAIL = 'GET_CODE_FAIL';
export const CHECK_CODE_SAGA = 'CHECK_CODE_SAGA';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_FAIL = 'CHECK_CODE_FAIL';
//修改密码
export const CHANGE_PSW_SAGA = 'CHANGE_PSW_SAGA';
export const CHANGE_PSW_SUCCESS = 'CHANGE_PSW_SUCCESS';
export const CHANGE_PSW_FAIL = 'CHANGE_PSW_FAIL';


//signup
export const GET_COMINFOSU_SAGA = 'GET_COMINFOSU_SAGA';
export const GET_COMINFOSU_SUCCESS = 'GET_COMINFOSU_SUCCESS';
export const GET_COMINFOSU_FAIL = 'GET_COMINFOSU_FAIL';

