import keyMirror from 'keymirror';

module.exports ={
  loginAction: keyMirror({
    CHANGE_LOGIN_PAGE_SAGA : null,
    CHANGE_LOGIN_PAGE : null,
    CHANGE_LOGIN_STORE_SAGA: null,
    CHANGE_LOGIN_STORE: null,
    LOGIN_FETCH : null,
    UPDATE_COUNT : null,
    BEGIN_COUNT : null,
    STOP_TASK : null,
    GET_COMMON_DATA_SAGA: null,//获取全电站需要的公共数据，例如getStations,getDeviecTypes,userName等
    // 登录
    USER_NAME_LOGIN_SAGA : null,
    USER_NAME_LOGIN_SUCCESS : null,
    USER_NAME_LOGIN_FAIL : null,
    GET_COMPINFO_SAGA : null,
    GET_COMPINFO_SUCCESS : null,
    GET_COMPINFO_FAIL : null,
    SEND_CODE_SAGA : null,
    SEND_CODE_SUCCESS : null,
    PHONE_CODE_LOGIN_SAGA : null,
    PHONE_CODE_LOGIN_SUCCESS : null,
    PHONE_CODE_LOGIN_FAIL : null,
    // 注册用验证
    CHECK_PHONE_REGISTER_SAGA: null,
    CHECK_PHONE_REGISTER_SUCCESS: null,
    CHECK_PHONE_REGISTER_FAIL: null,
    CHECK_ENTERPRISE_DOMAIN_SAGA: null,
    CHECK_ENTERPRISE_DOMAIN_SUCCESS:null,
    CHECK_ENTERPRISE_DOMAIN_FAIL: null,
    CHECK_ENTERPRISE_NAME_SAGA: null,
    CHECK_ENTERPRISE_NAME_SUCCESS: null,
    CHECK_ENTERPRISE_NAME_FAIL: null,
    REGISTER_ENTERPRISE_SAGA: null,
    REGISTER_ENTERPRISE_FAIL: null,
    CHECK_USER_REGISTER_SAGA: null,
    CHECK_USER_REGISTER_SUCCESS: null,
    CHECK_USER_REGISTER_FAIL: null,
    PHONE_CODE_REGISTER_SAGA: null,
    PHONE_CODE_REGISTER_SUCCESS: null,
    PHONE_CODE_REGISTER_FAIL: null,
    // 加入企业
    GET_JOININ_COMMON_SUCCESS: null,
    GET_ENTERPRISE_INFO_SAGA: null,
    GET_ENTERPRISE_INFO_SUCCESS: null,
    GET_ENTERPRISE_INFO_FAIL: null,
    JOIN_ENTERPRISE_SAGA: null,
    JOIN_ENTERPRISE_SUCCESS: null,
    JOIN_ENTERPRISE_FAIL: null,
    CHANGE_JOIN_STEP_SAGA: null,
    CHANGE_JOIN_STEP_SUCCESS: null,
    CHANGE_JOIN_STEP_FAIL: null,
    // 重置密码
    RESET_PASSWORD_SAGA: null,
    RESET_PASSWORD_FAIL: null,
    // 离开重置state
    RESET_LOGIN_STORE_SAGA: null,
    RESET_LOGIN_STORE_SUCCESS: null,
  })
}

