


export const CHANGE_PRELOGIN_PAGE = 'CHANGE_PRELOGIN_PAGE';
export const CHANGE_PRELOGIN_PAGE_SAGA = 'CHANGE_PRELOGIN_PAGE_SAGA';



export const CHANGE_LOGIN_PAGE = 'CHANGE_LOGIN_PAGE';

export const LOGIN_FETCH = 'LOGIN_FETCH';

export const GET_LOGIN_SAGA = 'GET_LOGIN_SAGA';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';