


export const CHANGE_PRELOGIN_PAGE = 'CHANGE_PRELOGIN_PAGE';
export const CHANGE_PRELOGIN_PAGE_SAGA = 'CHANGE_PRELOGIN_PAGE_SAGA';



export const CHANGE_LOGIN_PAGE = 'CHANGE_LOGIN_PAGE';

export const LOGIN_FETCH = 'LOGIN_FETCH';
export const UPDATE_COUNT = 'UPDATE_COUNT';
export const BEGIN_COUNT = 'BEGIN_COUNT';
export const STOP_TASK = 'BEGIN_COUNT';
// 密码登录
export const GET_LOGIN_SAGA = 'GET_LOGIN_SAGA';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAIL = 'GET_LOGIN_FAIL';
export const GET_COMPINFO_SAGA = 'GET_COMPINFO_SAGA';
export const GET_COMPINFO_SUCCESS = 'GET_COMPINFO_SUCCESS';
export const GET_COMPINFO_FAIL = 'GET_COMPINFO_FAIL';

// 手机验证码登录
export const SEND_CODE_SAGA = 'SEND_CODE_SAGA';
export const SEND_CODE_SUCCESS = 'SEND_CODE_SUCCESS';
export const SEND_CODE_FAIL = 'SEND_CODE_FAIL';
export const CHECK_CODE_SAGA = 'CHECK_CODE_SAGA';
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_FAIL = 'CHECK_CODE_FAIL';
