export const BEGIN_FETCH = 'BEGIN_FETCH';

export const GET_DEFECT_LIST_SAGA = "GET_DEFECT_LIST_SAGA";
export const GET_DEFECT_LIST_SUCCESS = 'GET_DEFECT_LIST_SUCCESS';
export const GET_DEFECT_LIST_FAIL = 'GET_DEFECT_LIST_FAIL';

export const DELETE_BATCH_DEFECT_SAGA = "DELETE_BATCH_DEFECT_SAGA";
export const DELETE_BATCH_DEFECT_SUCCESS = "DELETE_BATCH_DEFECT_SUCCESS";
export const DELETE_BATCH_DEFECT_FAIL = "DELETE_BATCH_DEFECT_FAIL";

export const GET_INSPECTION_LIST_SAGA = "GET_INSPECTION_LIST_SAGA";
export const GET_INSPECTION_LIST_SUCCESS = 'GET_INSPECTION_LIST_SUCCESS';
export const GET_INSPECTION_LIST_FAIL = 'GET_INSPECTION_LIST_FAIL';
