export const BEGIN_FETCH = 'BEGIN_FETCH';

export const GET_DEFECT_LIST_SAGA = "GET_DEFECT_LIST_SAGA";
export const GET_DEFECT_LIST_SUCCESS = 'GET_DEFECT_LIST_SUCCESS';
export const GET_DEFECT_LIST_FAIL = 'GET_DEFECT_LIST_FAIL';

export const DELETE_BATCH_DEFECT_SAGA = "DELETE_BATCH_DEFECT_SAGA";
export const DELETE_BATCH_DEFECT_SUCCESS = "DELETE_BATCH_DEFECT_SUCCESS";
export const DELETE_BATCH_DEFECT_FAIL = "DELETE_BATCH_DEFECT_FAIL";

export const GET_INSPECT_LIST_SAGA = "GET_INSPECT_LIST_SAGA";
export const GET_INSPECT_LIST_SUCCESS = 'GET_INSPECT_LIST_SUCCESS';
export const GET_INSPECT_LIST_FAIL = 'GET_INSPECT_LIST_FAIL';

export const SET_DEFECT_ID_SAGA = "SET_DEFECT_ID_SAGA";
export const SET_DEFECT_ID = "SET_DEFECT_ID";
export const GET_DEFECT_DETAIL_SAGA = "GET_DEFECT_DETAIL_SAGA";
export const GET_DEFECT_DETAIL_SUCCESS = "GET_DEFECT_DETAIL_SUCCESS";
export const GET_DEFECT_DETAIL_FAIL = "GET_DEFECT_DETAIL_FAIL";

export const SET_INSPECT_ID_SAGA = "SET_INSPECT_ID_SAGA";
export const SET_INSPECT_ID = "SET_INSPECT_ID";
export const GET_INSPECT_DETAIL_SAGA = "GET_INSPECT_DETAIL_SAGA";
export const GET_INSPECT_DETAIL_SUCCESS = "GET_INSPECT_DETAIL_SUCCESS";
export const GET_INSPECT_DETAIL_FAIL = "GET_INSPECT_DETAIL_FAIL";

export const GET_LANGUAGE_SAGA = "GET_LANGUAGE_SAGA";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_LANGUAGE_FAIL = "GET_LANGUAGE_FAIL";

