export const stationResourceAnalysisAction = {
 STATIONRESOURCESTATIONDATA_FETCH: Symbol(' STATIONRESOURCESTATIONDATA_FETCH'),//loading
  GET_STATIONRESOURCESTATIONDATA_FETCH_SUCCESS: Symbol('GET_STATIONRESOURCESTATIONDATA_FETCH_SUCCESS'),//请求成功 
  CHANGE_STATIONRESOURCESTATIONDATA_STORE_SAGA: Symbol('CHANGE_STATIONRESOURCESTATIONDATA_STORE_SAGA'),//改变默认参数
  CHANGE_STATIONRESOURCESTATIONDATA_STORE: Symbol('CHANGE_STATIONRESOURCESTATIONDATA_STORE'),//改变默认参数

}
